//
// Created by erwan on 31/05/2023.
//

#ifndef PROJET_ANNUEL_MULTLAYERPERCEPTRON_H
#define PROJET_ANNUEL_MULTLAYERPERCEPTRON_H
#include <Eigen/Dense>



#endif //PROJET_ANNUEL_MULTLAYERPERCEPTRON_H
